### PR TITLE
Update with new civilizations

### PR DESCRIPTION
**Pull request by AndyTheNerd**
This is a PR that includes all new civs from the Age2 DE release. This does not reflect on other files regarding units and structures, but it's a start.

### CODE REVIEW

**Comment by Patross** [comment]
uwu

**Comment by aalises** [comment]
Heyya! thanks for the update and contributing! ✨ . There are some errors when parsing the `civilizations` .csv though so it's crashing when generating the new data... this is the error log:

```
Line #9 (got 8 columns instead of 7)
Line #14 (got 10 columns instead of 7)
Line #19 (got 11 columns instead of 7)
Line #30 (got 9 columns instead of 7)
```

👀 The columns are delimited by `commas` and the different items inside the same column by `semicolons`. After that, you will have to regenerate and commit `data.db` (deleting it and running `python app.py` and making a request should generate it again).

**Comment by AndyTheNerd** [comment]
Sounds good!

**Comment by AndyTheNerd** [comment]
Sorry, I don't have a lot of free time these days. It should be really close, just some small spacing errors.

**Comment by aalises** [comment]
@AndyTheNerd updated here https://github.com/aalises/age-of-empires-II-api/pull/17 , closing this as it's a duplicate. Thanks for contributing!

**Pull request closed without merging**
